# Welcome to Jekyll!
#

title: VOSK Offline Speech Recognition API
email: nshmyrev@alphacephei.com
description: Accurate speech recognition for Android, iOS, Raspberry Pi and servers with Python, Java, C#, Swift and Node.
baseurl: "/vosk"
url: "https://alphacephei.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - build*.sh
  - README

google_analytics: UA-36804419-1
